import logging
from typing import List, Optional
from fastapi import APIRouter, Depends, Query, HTTPException
from app.core.security import require_api_key
from app.drivers.proxmox import proxmox_driver
from app.models.schemas import TemplateInfo

logger = logging.getLogger("orchestrator.api.templates")
router = APIRouter(prefix="/templates", tags=["Proxmox Templates"], dependencies=[Depends(require_api_key)])


@router.get("", response_model=List[TemplateInfo], summary="List available VM templates on Proxmox")
async def list_templates(node: Optional[str] = Query(None, description="Proxmox node name (default: pve)")):
    """
    Returns all templates found on the Proxmox node, classified into Linux and Windows.
    """
    try:
        return proxmox_driver.list_templates(node)
    except Exception as e:
        logger.error("Failed to query Proxmox templates: %s", e)
        raise HTTPException(status_code=502, detail=f"Failed to communicate with Proxmox VE: {e}")


@router.get("/nextid", summary="Get next available VM ID in Proxmox cluster")
async def get_next_vmid():
    """Returns the next available VMID generated by Proxmox cluster."""
    try:
        next_id = proxmox_driver.get_next_vmid()
        return {"next_vmid": next_id}
    except Exception as e:
        logger.error("Failed to query next VMID: %s", e)
        raise HTTPException(status_code=502, detail=f"Failed to query Proxmox cluster nextid: {e}")
